; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Source

  ```      UH102   .ASM				`S:\rac_edit UH102.asm
    `      LCD     .ASM				`S:\rac_edit LCD.asm
    `      TIME    .ASM				`S:\rac_edit TIME.ASM

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Include File

 ```       UH102 .INC				`S:\rac_edit UH102.INC
   `       RAM   .ASM				`S:\rac_edit RAM.ASM
   `       MACROS.ASM				`S:\rac_edit MACROS.ASM

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Misc. Files

 ```       UH102   .MTS				`S:\rac_edit UH102.mts
   `       UH102   .MAF				`S:\rac_edit UH102.maf
  ``       Version File.			`S:\RAC_EDIT UH102.ver


;