(10U
			Ultron, PIC.SCH
			Date : July 14, 1998

                   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
                >ÄÄ´  1 /MCLR                     RB7 40 ÃÄÄ   TTL   CS/INT Ch
		   ³					 ³
     CS   TTL   >ÄÄ´  2 RA0                       RB6 39 ÃÄÄ   TTL   CS/INT Ch
		   ³					 ³
     CS   TTL   >ÄÄ´  3 RA1                       RB5 38 ÃÄÄ   TTL   CS/INT Ch
		   ³					 ³
     CS   TTL   >ÄÄ´  4 RA2                       RB4 37 ÃÄÄ   TTL   CS/INT Ch
		   ³					 ³
     CS   TTL   >ÄÄ´  5 RA3                       RB3 36 ÃÄÄ<  TTL     CS
		   ³					 ³
   CS/CKI  ST   >ÄÄ´  6 RA4/T0CKI                 RB2 35 ÃÄÄ<  TTL     CS
		   ³					 ³
     CS   TTL   >ÄÄ´  7 RA5  /(/SS)               RB1 34 ÃÄÄ<  TTL     CS
		   ³					 ³
     CS    ST   <ÄÄ´  8 RE0  /(/RD)           RB0/INT 33 ÃÄÄ   TTL/ST  CS/INT
		   ³					 ³
     CS    ST   <ÄÄ´  9 RE1  /(/WR)               VDD 32 Ã
		   ³					 ³
     CS    ST   >ÄÄ´ 10 RE2  /(/CS)               VSS 31 Ã
		   ³					 ³
                   ´ 11 VDD               RD7 /(PSP7) 30 ÃÄÄ>   ST      D7
		   ³					 ³
                   ´ 12 VSS               RD6 /(PSP6) 29 ÃÄÄ>   ST      D6
		   ³					 ³
                   ´ 13 OSC1/CLKIN        RD5 /(PSP5) 28 ÃÄÄ>   ST      D5
       		   ³					 ³
                   ´ 14 OCS2/CLKOUT       RD4 /(PSP4) 27 ÃÄÄ>   ST      D4
		   ³					 ³
   CS/CK   ST   <ÄÄ´ 15 RC0/T1OSO/T1CKI  RC7/RX /(DT) 26 ÃÄÄ>   ST      RX
		   ³					 ³
   CS/CK   ST   <ÄÄ´ 16 RC1/TIOSI/CCP2   RC6/TX /(CK) 25 ÃÄÄ>   ST      TX
		   ³					 ³
   CS/CK   ST   <ÄÄ´ 17 RC2/CCP1           RC5 (/SDO) 24 ÃÄÄ    ST      CS
		   ³					 ³
   I2C-SCL ST   <ÄÄ´ 18 RC3 (/SCK) /SCL RC4(/SDI)/SDA 23 ÃÄÄ<   ST    I2C-SDA
   		   ³					 ³
     D0    ST   <ÄÄ´ 19 RD0 /(PSP0)       RD3 /(PSP3) 22 ÃÄÄ>   ST      D3
		   ³					 ³
     D1    ST   >ÄÄ³ 20 RD1 /(PSP1)       RD2 /(PSP2) 21 ÃÄÄ    ST      D2
                   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

	Dx = Data Buss
	CS = A chip Select for an 8bit latch In or out
	
