; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Source

  ```      ULTRON  .ASM				`S:\rac_edit ULTRON.asm
    `      LCD     .ASM				`S:\rac_edit LCD.asm
    `      TIME    .ASM				`S:\rac_edit TIME.ASM

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Include File

 ```       ULTRON.INC				`S:\rac_edit ULTRON.INC
   `       RAM   .ASM				`S:\rac_edit RAM.ASM
   `       MACROS.ASM				`S:\rac_edit MACROS.ASM

; -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
;          Edit Misc. Files

 ```       ULTRON.MTS				`S:\rac_edit ULTRON.mts
   `       ULTRON.MAF				`S:\rac_edit ULTRON.maf
  ``       Version File.			`S:\RAC_EDIT ULTRON.ver


;